export type Character = { slug: string; displayName: string };

export const CHARACTERS: Character[] = [
  { slug: "mario", displayName: "Mario" },
  { slug: "luigi", displayName: "Luigi" },
  { slug: "peach", displayName: "Peach" },
  { slug: "daisy", displayName: "Daisy" },
  { slug: "rosalina", displayName: "Rosalina" },
  { slug: "pauline", displayName: "Pauline" },
  { slug: "yoshi", displayName: "Yoshi" },
  { slug: "birdo", displayName: "Birdo" },
  { slug: "toad", displayName: "Toad" },
  { slug: "pro-racer-toad", displayName: "Pro Racer Toad" },
  { slug: "toadette", displayName: "Toadette" },
  { slug: "koopa-troopa", displayName: "Koopa Troopa" },
  { slug: "shy-guy", displayName: "Shy Guy" },
  { slug: "lakitu", displayName: "Lakitu" },
  { slug: "king-boo", displayName: "King Boo" },
  { slug: "donkey-kong", displayName: "Donkey Kong" },
  { slug: "wario", displayName: "Wario" },
  { slug: "waluigi", displayName: "Waluigi" },
  { slug: "bowser", displayName: "Bowser" },
  { slug: "bowser-jr", displayName: "Bowser Jr." },
  { slug: "baby-mario", displayName: "Baby Mario" },
  { slug: "baby-luigi", displayName: "Baby Luigi" },
  { slug: "baby-peach", displayName: "Baby Peach" },
  { slug: "baby-daisy", displayName: "Baby Daisy" },
  { slug: "baby-rosalina", displayName: "Baby Rosalina" },
  { slug: "nabbit", displayName: "Nabbit" },
  { slug: "goomba", displayName: "Goomba" },
  { slug: "dry-bones", displayName: "Dry Bones" },
  { slug: "piranha-plant", displayName: "Piranha Plant" },
  { slug: "wiggler", displayName: "Wiggler" },
  { slug: "hammer-bro", displayName: "Hammer Bro" },
  { slug: "sidestepper", displayName: "Sidestepper" },
  { slug: "monty-mole", displayName: "Monty Mole" },
  { slug: "cheep-cheep", displayName: "Cheep Cheep" },
  { slug: "pokey", displayName: "Pokey" },
  { slug: "stingby", displayName: "Stingby" },
  { slug: "cow", displayName: "Cow" },
  { slug: "snowman", displayName: "Snowman" },
  { slug: "para-biddybud", displayName: "Para-Biddybud" },
  { slug: "penguin", displayName: "Penguin" },
  { slug: "chargin-chuck", displayName: "Chargin' Chuck" },
  { slug: "cataquack", displayName: "Cataquack" },
  { slug: "coin-coffer", displayName: "Coin Coffer" },
  { slug: "conkdor", displayName: "Conkdor" },
  { slug: "dolphin", displayName: "Dolphin" },
  { slug: "fish-bone", displayName: "Fish Bone" },
  { slug: "peepa", displayName: "Peepa" },
  { slug: "pianta", displayName: "Pianta" },
  { slug: "rocky-wrench", displayName: "Rocky Wrench" },
  { slug: "spike", displayName: "Spike" },
  { slug: "swoop", displayName: "Swoop" },
];

export function isValidAvatarSlug(slug: string): boolean {
  return CHARACTERS.some((c) => c.slug === slug);
}